### PR TITLE
Fixed compatibility with CommonLib

### PR DESCRIPTION
**Pull request by JohnyCilohokla**

### CODE REVIEW

**Comment by mercorii** [comment]
Merged! 

Btw, was the main point of the commit that the GUI will be only instanced when Eternus.IsClient?

Or was it problematic that the GUI file was originally loaded at all in all cases? Naturally, there isn't much use to include it in server environments.

Mainly I'm pondering about the require call. I'm not totally sure what I think about requiring additional files in the middle of the file. I kind of like as a coding convention to declare them in the beginning of the file, so that it's easy to see at one glance what are the dependencies.

Then again returning the object from the file and chaining the new() call to the require was a nice trick.

**Comment by JohnyCilohokla** [comment]
It's actually the order in which the CommonLib forces the game to load, to implement hooks I need to initialize mods early, before GUI and world gen is initialized.

Since lua is all global requiring or including a file is fine anywhere, the reason I have put it in the Initialize function is to make sure it is included/required later on when it is needed (to make sure all other needed systems had a chance to load first).

**Comment by JohnyCilohokla** [comment]
oh ya you could probably change the require to include("Scripts/UI/PointOfInterestCompass.lua") and it will work the same way

**Comment by mercorii** [comment]
Ah yes, you mentioned earlier in the other thread that the problem was in the order the files were loaded.

Do you think this will be a permanent requirement? That GUI files need to be loaded after other files when using CommonLib?

**Comment by JohnyCilohokla** [comment]
Actually CommonLib will not be a permanent solution, we are working on modding improvements atm.

**Pull request merged**
